################################################################
# This file lists variables used in configuring dc3 evaluation 
################################################################

#############
## List of start dates

start_times:
  - "2022-11-01"
  - "2023-11-01"

end_times:
  - "2023-05-01"
  - "2024-05-01"

sources:
  - dataset: amsr2
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/AMSR2"
    s3_key: *WASABI_KEY # TODO: Define this
    s3_secret_key: *WASABI_SECRET_KEY # TODO: Define this
    file_pattern: "**/asi-AMSR2-n3125-*-v5.4.zarr" # [YYYY]/asi-AMSR2-n3125-[YYMMDD]-v5.4.zarr
    keep_variables:
    - "x"
    - "y"
    - "z"
    - "lat"
    - "lon"
    eval_variables:
    - "z"

  - dataset: iabp
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/IABP"
    s3_key: *WASABI_KEY # TODO: Define this
    s3_secret_key: *WASABI_SECRET_KEY # TODO: Define this
    file_pattern: "LEVEL1_*.zarr" # LEVEL1_[YYYY].zarr
    keep_variables:
    - "BuoyID"
    - "lat" 
    - "lon"
    - "n_points"
    - "time"
    - "BP" # Barometric Pressure
    - "Ta" # Air Temperature (°C) typically at 1m
    - "Th" # Hull Temperature (°C) inside the buoy
    - "Ts" # Surface Temperature (°C)
    eval_variables:
    - "Ts"

  - dataset: modis
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/MODIS"
    s3_key: *WASABI_KEY # TODO: Define this
    s3_secret_key: *WASABI_SECRET_KEY # TODO: Define this
    file_pattern: "*_ArcLeads.zarr" # [YYYY][YY+1]_ArcLeads.zarr
    keep_variables:
    - "lat"
    - "lon"
    - "time"
    - "x"
    - "y"
    - "leadmap"
    eval_variables:
    - "leadmap"
