################################################################
# This file lists variables used in configuring dc3 evaluation 
################################################################
##  WASABI credentials
define: &WASABI_KEY
  
define: &WASABI_SECRET_KEY
  
  
############################# GENERAL DC PARAMETERS ###################################

max_samples: 
max_cache_files: 1000
delta_time: 12

n_days_forecast: 10
# n_days_forecast: 181 # Seasonal forecast # TODO: Uncomment when debugged
n_days_interval: 365 # One for each year

############################# PARALLELIZATION ###################################

batch_size: 32
n_parallel_workers: 8
nthreads_per_worker: 4
memory_limit_per_worker: "6GB"

############################# DATA FILTERS ###################################

## List of start dates
# start_times:
start_time: "2020-11-01"
  # - "202'-11-01"

# end_times:
end_time: "2020-11-11" # 10 days for debugging 
# end_time: "2021-05-01" # TODO: Uncomment when debugged
  # - "2024-05-01"

# Target region coordinates (in meters)
# NOTE: Coordinates in EPSG:3413 (Arctic) grid
#       x range from -3 850 000 to 3 750 000
#       y range from -5 350 000 to 5 850 000

min_x: -3850000
max_x: 3750000
min_y: -5350000
max_y: 5850000

# Path to catalog file
# catalog_path: ""

############################# DATASETS ###################################

sources:
  - dataset: amsr2
    time_tolerance: 12
    metrics:
      - "rmsd"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/AMSR2_1D-time"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/asi-AMSR2-n3125-*-v5.4.zarr" # [YYYY]/asi-AMSR2-n3125-[YYMMDD]-v5.4.zarr
    keep_variables:
    - "y"
    - "x"
    - "time"
    - "z"
    # - "lat"
    # - "lon"
    eval_variables:
    - "z"

  - dataset: iabp
    observation_dataset: true
    time_tolerance: 12
    metrics:
      - "rmsd"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/IABP"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "LEVEL1_*.zarr" # LEVEL1_[YYYY].zarr
    keep_variables:
    - "BuoyID"
    - "lat" 
    - "lon"
    - "n_points"
    - "time"
    - "BP" # Barometric Pressure
    - "Ta" # Air Temperature (°C) typically at 1m
    - "Th" # Hull Temperature (°C) inside the buoy
    - "Ts" # Surface Temperature (°C)
    eval_variables:
    - "Ts"

  - dataset: modis
    time_tolerance: 12
    metrics:
      - "rmsd"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/MODIS"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "*_ArcLeads.zarr" # [YYYY][YY+1]_ArcLeads.zarr
    keep_variables:
    - "lat"
    - "lon"
    - "time"
    - "x"
    - "y"
    - "leadmap"
    eval_variables:
    - "leadmap"

  - dataset: topaz
    observation_dataset: false
    metrics:
      - "rmsd"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC3/TOPAZ"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/**/*.zarr"
    keep_variables:
    - "y"
    - "x"
    - "time"
    - "siconc"
    eval_variables:
    - "siconc"
